################################################################################
# MASTER SYNTHETIC PIPELINE
#
# Purpose:
#   Run the complete UAMS synthetic-data analysis pipeline from Step 01 through
#   Step 33 in the required order.
#
# This script:
#   1. Verifies that the working directory is the synthetic-test project root.
#   2. Verifies that the synthetic raw UAMS data are available.
#   3. Runs all preprocessing, model-training, scoring, survival-analysis,
#      clustering, heatmap, clinical-comparison, and Cox-regression scripts.
#   4. Recreates all processed ExpressionSets, models, QC files, figures,
#      source-data files, and Table 1 results from the synthetic dataset.
#
# Intended use:
#   This is the master runner for validating that the complete analysis workflow
#   is reproducible using synthetic data only.
#
# Run from the synthetic-test project root with:
#
#   source("scripts/master-pipeline/run-synthetic-pipeline.R")
#
# Important:
#   - This script must be run from the synthetic-test project root.
#   - Do not run this script from inside the scripts/ folder.
#   - Do not run this script from the real-data project root.
#   - The synthetic-test project root must contain:
#       data/
#       scripts/
#       models/
#       results/
#   - Synthetic raw input files must be located in:
#       data/raw/uams/
#   - Scripts are executed sequentially because later steps depend on files
#     generated by earlier steps.
#   - If a step fails, stop the pipeline and resolve that error before
#     continuing to later steps.
#   - This pipeline is intended for reproducibility testing and does not use
#     real patient-level expression data.
################################################################################


################################################################################
# 1. VERIFY SYNTHETIC PROJECT ROOT
################################################################################

PROJECT_ROOT <- normalizePath(
  getwd(),
  winslash = "/",
  mustWork = TRUE
)

if (basename(PROJECT_ROOT) != "synthetic-test") {
  stop(
    "\n",
    "The synthetic pipeline must be run from the synthetic-test project root.\n\n",
    "Current working directory:\n",
    PROJECT_ROOT,
    "\n\n",
    "Expected project folder:\n",
    "synthetic-test\n"
  )
}


################################################################################
# 2. VERIFY REQUIRED PROJECT DIRECTORIES
################################################################################

REQUIRED_DIRS <- c(
  "data",
  "scripts"
)

MISSING_DIRS <- REQUIRED_DIRS[
  !dir.exists(REQUIRED_DIRS)
]

if (length(MISSING_DIRS) > 0) {
  stop(
    "\n",
    "Required project folder(s) are missing:\n",
    paste(MISSING_DIRS, collapse = ", "),
    "\n"
  )
}


################################################################################
# 3. VERIFY SYNTHETIC RAW DATA DIRECTORY
################################################################################

SYNTHETIC_DATA_DIR <- file.path(
  PROJECT_ROOT,
  "data",
  "raw",
  "uams"
)

if (!dir.exists(SYNTHETIC_DATA_DIR)) {
  stop(
    "\n",
    "Synthetic UAMS raw-data folder was not found:\n",
    SYNTHETIC_DATA_DIR,
    "\n"
  )
}


################################################################################
# 4. VERIFY REQUIRED SYNTHETIC INPUT FILES
################################################################################

REQUIRED_RAW_FILES <- c(
  "expression-rnas-mgus.csv",
  "expression-rnas-ndmm.csv",
  "expression-rnbx-mgus.csv",
  "expression-rnbx-ndmm.csv",
  "features.csv",
  "phenotype.csv",
  "fish-1q-1p-gep-bl-overlap.csv"
)

MISSING_RAW_FILES <- REQUIRED_RAW_FILES[
  !file.exists(
    file.path(
      SYNTHETIC_DATA_DIR,
      REQUIRED_RAW_FILES
    )
  )
]

if (length(MISSING_RAW_FILES) > 0) {
  stop(
    "\n",
    "Required synthetic raw-data file(s) are missing:\n",
    paste(MISSING_RAW_FILES, collapse = "\n"),
    "\n"
  )
}


################################################################################
# 5. REPORT PROJECT AND INPUT FILES
################################################################################

cat(
  "\n",
  "============================================================\n",
  "SYNTHETIC PIPELINE\n",
  "============================================================\n\n",
  "Project root:\n",
  PROJECT_ROOT,
  "\n\n",
  "Synthetic raw-data directory:\n",
  SYNTHETIC_DATA_DIR,
  "\n\n",
  "Synthetic raw-data files:\n"
)

print(
  list.files(
    SYNTHETIC_DATA_DIR
  )
)

cat(
  "\n",
  "Starting pipeline...\n\n"
)


################################################################################
# 6. RUN PIPELINE
################################################################################

source("scripts/01_check-missing-values.R")
source("scripts/02_prepare-uams-data.R")
source("scripts/03_train-gep1q-elastic-net-cv.R")
source("scripts/04_evaluate-gep1q-penalized-heldout-confusion-matrix.R")
source("scripts/05_apply-gep1q-lasso-score.R")
source("scripts/06_add-fish-data.R")
source("scripts/07_train-and-apply-polyig-score.R")
source("scripts/08_classify-pc-me-genes.R")
source("scripts/09_fig1a-gep70-km.R")
source("scripts/10_fig1b-cox-volcano.R")
source("scripts/11_fig1c-consensus-clustering-heatmap.R")
source("scripts/12_fig1d_cluster_enrichment.R")
source("scripts/13_fish1q-ttp-km.R")
source("scripts/14_unigh-ttp-km.R")
source("scripts/15_fish1q-unigh-ttp-km.R")
source("scripts/16_gep1q-ttp-km.R")
source("scripts/17_polyig-ttp-km.R")
source("scripts/18_fig1e-gep1q-polyig-km.R")
source("scripts/19_add-uams-binary-pdata-columns.R")
source("scripts/20_add-uams-composite-rnas-groups.R")
source("scripts/21_match-rnas-groups-to-rnbx-by-patid.R")
source("scripts/22_rnbx-mgus-vs-gep70-limma.R")
source("scripts/23_fig2b_Microenvironment_Heatmap.R")
source("scripts/24_fig2a_Microenvironment_Heatmap.R")
source("scripts/25_fig3a-gep1q-polyig-km-tt2.R")
source("scripts/26_fig3b-gep1q-polyig-km-tt3plus.R")
source("scripts/27_Fig4A-D_4_6_8yr_Full_followup.R")
source("scripts/28_fig5a-gep1q-polyig-km.R")
source("scripts/29_fig5b-fish1q-unigh-ttp-km.R")
source("scripts/30_overlay-gep-and-clinical-ttr-curves.R")
source("scripts/31_clinical-gep-confusion-matrix.R")
source("scripts/32_univariate-cox.R")
source("scripts/33_multivariate-cox.R")


################################################################################
# 7. COMPLETE
################################################################################

cat(
  "\n",
  "============================================================\n",
  "SYNTHETIC PIPELINE COMPLETE\n",
  "============================================================\n",
  "\n",
  "Project root:\n",
  PROJECT_ROOT,
  "\n"
)
